version: '3.9'

services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}

  wb_app:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - ./.env.prod
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      - db


