# Generated by Django 4.0.4 on 2022-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.PositiveBigIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('goods_name', models.CharField(max_length=255)),
                ('price_without_discount', models.PositiveIntegerField()),
                ('price_with_discount', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.PositiveBigIntegerField()),
                ('price_without_discount', models.PositiveIntegerField()),
                ('price_with_discount', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=255)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
